import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedSeenoevil180gmailcomWidget2.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedEmailIDWidget1.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedSignInWidget.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedGroup82Widget.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedRectangle237Widget.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedWelcomeBackWidget.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedSignUpWidget1.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedDonthaveanAccountWidget.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedLogintoyouraccountWidget.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/Generated31Widget1.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedVectorWidget131.dart';
import 'package:flutterapp/teamapp/generatedloginwidget/generated/GeneratedForgotPasswordWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame LOG IN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLOGINWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.5327102803738317;

                                final double height =
                                    constraints.maxHeight * 0.15982721382289417;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2336448598130841,
                                      y: constraints.maxHeight *
                                          0.12958963282937366,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated31Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 219.0,
                              height: 29.0,
                              child: GeneratedGroup82Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 346.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 580.0,
                              child: GeneratedRectangle237Widget(),
                            ),
                            Positioned(
                              left: 94.0,
                              top: 376.0,
                              right: null,
                              bottom: null,
                              width: 225.0,
                              height: 43.0,
                              child: GeneratedWelcomeBackWidget(),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 417.0,
                              right: null,
                              bottom: null,
                              width: 190.0,
                              height: 25.0,
                              child: GeneratedLogintoyouraccountWidget(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 486.0,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 72.0,
                              child: GeneratedRectangle11Widget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 463.0,
                              right: null,
                              bottom: null,
                              width: 74.0,
                              height: 25.0,
                              child: GeneratedEmailIDWidget1(),
                            ),
                            Positioned(
                              left: 56.0,
                              top: 507.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 34.0,
                              child: GeneratedSeenoevil180gmailcomWidget2(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 602.0,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 72.0,
                              child: GeneratedRectangle12Widget1(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 579.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 28.0,
                              child: GeneratedPasswordWidget1(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 626.0,
                              right: null,
                              bottom: null,
                              width: 252.0,
                              height: 40.0,
                              child: GeneratedWidget2(),
                            ),
                            Positioned(
                              left: 241.0,
                              top: 682.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 25.0,
                              child: GeneratedForgotPasswordWidget(),
                            ),
                            Positioned(
                              left: 66.0,
                              top: 852.0,
                              right: null,
                              bottom: null,
                              width: 202.0,
                              height: 25.0,
                              child: GeneratedDonthaveanAccountWidget(),
                            ),
                            Positioned(
                              left: 274.0,
                              top: 852.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 25.0,
                              child: GeneratedSignUpWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.5514018691588785;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        236.0;

                                double percentHeight = 0.06695464362850972;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        62.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.1985981308411215,
                                      translateY: constraints.maxHeight *
                                          0.8110151187904968,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget131())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 764.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 37.0,
                              child: GeneratedSignInWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
