import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Cap
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCapWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.4000000059604645,
      child: Container(
        width: 1.3329999446868896,
        height: 4.0,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M2.22045e-16 0L2.22045e-16 4C0.394829 3.83473 0.731967 3.5564 0.969 3.2C1.20578 2.84454 1.3324 2.42711 1.333 2C1.3324 1.57289 1.20578 1.15546 0.969 0.8C0.731967 0.443604 0.394829 0.165266 0 3.33067e-16L2.22045e-16 0Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    ));
  }
}
