import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedBMW2021Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedAmankwaMotorsWidget2.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedNotificationsWidget2.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedAnthonyYeboahWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedUnsplasheTuK4z2LhYWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedGroup57Widget3.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedRectangle105Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedVectorWidget76.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedKofiAburiWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedChatsWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedSuziki2020Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/Generated330pmWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedNotificationsWidget6.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/Generated320amWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedNotificationsWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/Generated1201amWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedNotificationsWidget8.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedNotificationsWidget3.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedEmilyAsanteWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedUnsplashorWPUp0fRI4Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedAkariconschevrondownWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedRectangle108Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedToyotaSUVWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedRectangle106Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedRectangle104Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedHondaAchordWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedRectangle107Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedActiveWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/Generated155pmWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedRectangle109Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedNotificationsWidget7.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedCanyoucometomyofficeWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedHelloWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedRectangle100Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedNotificationsWidget4.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedUnsplash62wQhEghaw0Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedWhereareyoulocatedWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedNotificationsWidget5.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedGroup56Widget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedMyMessagesWidget.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget/generated/GeneratedHowmuchdoyouwanttopayWidget.dart';

/* Frame message
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 248, 248, 248),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 103.0,
                              child: GeneratedRectangle100Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 42.0,
                              child: GeneratedGroup57Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.441588785046729;

                                final double height =
                                    constraints.maxHeight * 0.03995680345572354;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2827102803738318,
                                      y: constraints.maxHeight *
                                          0.09935205183585313,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedMyMessagesWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child: GeneratedRectangle104Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child: GeneratedRectangle105Widget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 154.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 28.0,
                              child: GeneratedChatsWidget(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 28.0,
                              child: GeneratedActiveWidget(),
                            ),
                            Positioned(
                              left: 244.0,
                              top: 154.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 282.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget1(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 366.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget2(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 460.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget3(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 549.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget4(),
                            ),
                            Positioned(
                              left: 106.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget5(),
                            ),
                            Positioned(
                              left: 106.0,
                              top: 377.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget6(),
                            ),
                            Positioned(
                              left: 106.0,
                              top: 471.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget7(),
                            ),
                            Positioned(
                              left: 109.0,
                              top: 560.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget8(),
                            ),
                            Positioned(
                              left: 377.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedAkariconschevrondownWidget(),
                            ),
                            Positioned(
                              left: -18.0,
                              top: 231.0,
                              right: null,
                              bottom: null,
                              width: 458.0,
                              height: 90.0,
                              child: GeneratedRectangle106Widget(),
                            ),
                            Positioned(
                              left: -18.0,
                              top: 319.0,
                              right: null,
                              bottom: null,
                              width: 458.0,
                              height: 90.0,
                              child: GeneratedRectangle107Widget(),
                            ),
                            Positioned(
                              left: -18.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 458.0,
                              height: 90.0,
                              child: GeneratedRectangle108Widget(),
                            ),
                            Positioned(
                              left: -15.0,
                              top: 497.0,
                              right: null,
                              bottom: null,
                              width: 458.0,
                              height: 90.0,
                              child: GeneratedRectangle109Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 241.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedUnsplash62wQhEghaw0Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedUnsplasheTuK4z2LhYWidget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 420.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedUnsplashorWPUp0fRI4Widget(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 25.0,
                              child: GeneratedKofiAburiWidget(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 25.0,
                              child: GeneratedAnthonyYeboahWidget(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 422.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 25.0,
                              child: GeneratedEmilyAsanteWidget(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 511.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 25.0,
                              child: GeneratedAmankwaMotorsWidget2(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 272.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 23.0,
                              child: GeneratedToyotaSUVWidget(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 356.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 23.0,
                              child: GeneratedBMW2021Widget(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 448.0,
                              right: null,
                              bottom: null,
                              width: 98.0,
                              height: 23.0,
                              child: GeneratedSuziki2020Widget(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 537.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 23.0,
                              child: GeneratedHondaAchordWidget(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 189.0,
                              height: 20.0,
                              child: GeneratedCanyoucometomyofficeWidget(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 20.0,
                              child: GeneratedWhereareyoulocatedWidget(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 472.0,
                              right: null,
                              bottom: null,
                              width: 211.0,
                              height: 20.0,
                              child: GeneratedHowmuchdoyouwanttopayWidget(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 561.0,
                              right: null,
                              bottom: null,
                              width: 41.0,
                              height: 23.0,
                              child: GeneratedHelloWidget(),
                            ),
                            Positioned(
                              left: 338.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 76.0,
                              height: 25.0,
                              child: Generated330pmWidget(),
                            ),
                            Positioned(
                              left: 338.0,
                              top: 336.0,
                              right: null,
                              bottom: null,
                              width: 76.0,
                              height: 25.0,
                              child: Generated155pmWidget(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 425.0,
                              right: null,
                              bottom: null,
                              width: 76.0,
                              height: 25.0,
                              child: Generated320amWidget(),
                            ),
                            Positioned(
                              left: 332.0,
                              top: 514.0,
                              right: null,
                              bottom: null,
                              width: 87.0,
                              height: 25.0,
                              child: Generated1201amWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.16355140186915887;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        70.0;

                                double percentHeight = 0.0755939524838013;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        70.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.07009345794392523,
                                      translateY: constraints.maxHeight *
                                          0.5485961123110151,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget76())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 868.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 58.0,
                              child: GeneratedGroup56Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
