import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedMessageWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVectorWidget82.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedChecktheitembeforebuyingitWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVectorWidget93.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVectorWidget84.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedGroup55Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedFlatcoloriconsgalleryWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedIctwotonesafetycheckWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedDontpayinadvanceWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVoicemessageWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedRectangle100Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedChatwiththesellertoclearifyitemWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedEvaarrowbackfillWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVectorWidget92.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedEllipse44Widget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedMeetinasafepublicplaceWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedDetailsWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedGroup57Widget4.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedRectangle103Widget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVectorWidget90.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVectorWidget83.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVectorWidget91.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVectorWidget88.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedRectangle101Widget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVectorWidget89.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedSafetyTipsWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedRectangle102Widget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedSeeallSafetytipsWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedAvoidoffersthatlookunrealisticWidget.dart';
import 'package:flutterapp/teamapp/generatedmessage1widget/generated/GeneratedVectorWidget87.dart';

/* Frame message 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessage1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 38.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 110.0,
                              child: GeneratedRectangle100Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.14953271028037382;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        64.0;

                                double percentHeight = 0.0685224842046816;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        63.451820373535156;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.1261682242990654,
                                      translateY: constraints.maxHeight *
                                          0.07451403887688984,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget82())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.42629441591066736;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        182.45401000976562;

                                double percentHeight = 0.01564175006380349;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        14.484260559082031;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.2967289719626168,
                                      translateY: constraints.maxHeight *
                                          0.08639308855291576,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget83())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.09128502819025627;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        39.06999206542969;

                                double percentHeight = 0.012201288606384145;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        11.298393249511719;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.2967289719626168,
                                      translateY: constraints.maxHeight *
                                          0.11663066954643629,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget84())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 405.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 5.0,
                              height: 23.0,
                              child: GeneratedGroup55Widget1(),
                            ),
                            Positioned(
                              left: 85.0,
                              top: 205.0,
                              right: null,
                              bottom: null,
                              width: 258.0,
                              height: 253.0,
                              child: GeneratedRectangle101Widget(),
                            ),
                            Positioned(
                              left: 123.0,
                              top: 221.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 53.0,
                              child: GeneratedIctwotonesafetycheckWidget(),
                            ),
                            Positioned(
                              left: 173.0,
                              top: 237.0,
                              right: null,
                              bottom: null,
                              width: 125.0,
                              height: 31.0,
                              child: GeneratedSafetyTipsWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.016355140186915886;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) / 7.0;

                                double percentHeight = 0.00755939524838013;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        7.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.2219626168224299,
                                      translateY: constraints.maxHeight *
                                          0.31641468682505397,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget87())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.016355140186915886;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) / 7.0;

                                double percentHeight = 0.00755939524838013;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        7.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.2219626168224299,
                                      translateY: constraints.maxHeight *
                                          0.3444924406047516,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget88())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.016355140186915886;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) / 7.0;

                                double percentHeight = 0.00755939524838013;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        7.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.2219626168224299,
                                      translateY: constraints.maxHeight *
                                          0.3855291576673866,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget89())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.016355140186915886;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) / 7.0;

                                double percentHeight = 0.00755939524838013;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        7.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.2219626168224299,
                                      translateY: constraints.maxHeight *
                                          0.4146868250539957,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget90())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.016355140186915886;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) / 7.0;

                                double percentHeight = 0.00755939524838013;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        7.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.2219626168224299,
                                      translateY: constraints.maxHeight *
                                          0.44384449244060475,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget91())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 287.0,
                              right: null,
                              bottom: null,
                              width: 213.0,
                              height: 20.0,
                              child:
                                  GeneratedAvoidoffersthatlookunrealisticWidget(),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 223.0,
                              height: 20.0,
                              child:
                                  GeneratedChatwiththesellertoclearifyitemWidget(),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 351.0,
                              right: null,
                              bottom: null,
                              width: 189.0,
                              height: 20.0,
                              child: GeneratedMeetinasafepublicplaceWidget(),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 378.0,
                              right: null,
                              bottom: null,
                              width: 205.0,
                              height: 20.0,
                              child:
                                  GeneratedChecktheitembeforebuyingitWidget(),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 405.0,
                              right: null,
                              bottom: null,
                              width: 138.0,
                              height: 20.0,
                              child: GeneratedDontpayinadvanceWidget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 433.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 20.0,
                              child: GeneratedSeeallSafetytipsWidget(),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 329.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 23.0,
                              child: GeneratedDetailsWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.3107476635514019;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        133.0;

                                double percentHeight = 0.06263498920086392;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        58.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.6448598130841121,
                                      translateY: constraints.maxHeight *
                                          0.7915766738660908,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget92())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.2029205750082141;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        86.85000610351562;

                                double percentHeight = 0.018183730848407128;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        16.838134765625;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.7032710280373832,
                                      translateY: constraints.maxHeight *
                                          0.8131749460043196,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget93())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 827.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 99.0,
                              child: GeneratedRectangle102Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 843.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 58.0,
                              child: GeneratedRectangle103Widget(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 854.0,
                              right: null,
                              bottom: null,
                              width: 35.0,
                              height: 35.0,
                              child: GeneratedEllipse44Widget(),
                            ),
                            Positioned(
                              left: 88.0,
                              top: 861.0,
                              right: null,
                              bottom: null,
                              width: 114.0,
                              height: 33.0,
                              child: GeneratedMessageWidget1(),
                            ),
                            Positioned(
                              left: 296.0,
                              top: 854.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 40.0,
                              child: GeneratedVoicemessageWidget(),
                            ),
                            Positioned(
                              left: 345.0,
                              top: 854.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 40.0,
                              child: GeneratedFlatcoloriconsgalleryWidget(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 42.0,
                              child: GeneratedGroup57Widget4(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 87.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedEvaarrowbackfillWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
