import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedVectorWidget329.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedAkariconssearchWidget5.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedRectangle97Widget3.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedGroup73Widget1.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedHotDealsWidget3.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedVectorWidget331.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedRectangle162Widget1.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedFrame56Widget5.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedGroup55Widget10.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedEllipse4Widget1.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedSearchWidget5.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/Generated\$79000Widget6.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedGroup56Widget3.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedNowWidget17.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedFrame55Widget3.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedAntdesignclosecircleoutlinedWidget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedEllipse3Widget1.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedStatusBarWidget22.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedUSEDENGINE10DISCOUNTWidget3.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedFrame56Widget6.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedCarbonlogokeybaseWidget1.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedVectorWidget330.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedFrame56Widget7.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/GeneratedGroup64Widget1.dart';
import 'package:flutterapp/teamapp/generatedcartwidget1/generated/Generated\$50000Widget4.dart';

/* Frame Cart
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCartWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 252, 252, 252),
                              ),
                            ),
                            Positioned(
                              left: 384.0,
                              top: 455.6836853027344,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 60.0,
                              child: GeneratedUSEDENGINE10DISCOUNTWidget3(),
                            ),
                            Positioned(
                              left: 388.0,
                              top: 472.6836853027344,
                              right: null,
                              bottom: null,
                              width: 114.0,
                              height: 40.0,
                              child: Generated$50000Widget4(),
                            ),
                            Positioned(
                              left: 501.0,
                              top: 480.6836853027344,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 28.0,
                              child: GeneratedNowWidget17(),
                            ),
                            Positioned(
                              left: 394.0,
                              top: 440.6836853027344,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 34.0,
                              child: Generated$79000Widget6(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 58.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 59.0,
                              child: GeneratedEllipse1Widget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 62.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 51.0,
                              child: GeneratedEllipse2Widget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 62.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 51.0,
                              child: GeneratedEllipse3Widget1(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 65.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedEllipse4Widget1(),
                            ),
                            Positioned(
                              left: 28.423828125,
                              top: 69.9326171875,
                              right: null,
                              bottom: null,
                              width: 34.47944641113281,
                              height: 34.47944641113281,
                              child: GeneratedCarbonlogokeybaseWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 42.0,
                              child: GeneratedStatusBarWidget22(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 204.0,
                              right: null,
                              bottom: null,
                              width: 395.0,
                              height: 47.0,
                              child: GeneratedFrame55Widget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 139.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 53.0,
                              child: GeneratedRectangle97Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.07469162985543225;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        31.968017578125;

                                double percentHeight = 0.030420101487095876;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        28.16901397705078;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.8014018691588785,
                                      translateY: constraints.maxHeight *
                                          0.08531317494600432,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget329())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.020746961932316003;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        8.87969970703125;

                                double percentHeight = 0.01019682585549406;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        9.4422607421875;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.8714953271028038,
                                      translateY: constraints.maxHeight *
                                          0.08315334773218143,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget330())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.022987650933666764;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        9.838714599609375;

                                double percentHeight = 0.0020388856562373447;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        1.8880081176757812;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.8434579439252337,
                                      translateY: constraints.maxHeight *
                                          0.08639308855291576,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget331())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 398.0,
                              top: 81.0,
                              right: null,
                              bottom: null,
                              width: 5.0,
                              height: 23.0,
                              child: GeneratedGroup55Widget10(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 153.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 34.0,
                              child: GeneratedSearchWidget5(),
                            ),
                            Positioned(
                              left: 362.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedAkariconssearchWidget5(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 263.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 247.0,
                              child: GeneratedFrame56Widget5(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 519.0,
                              right: null,
                              bottom: null,
                              width: 87.0,
                              height: 25.0,
                              child: GeneratedHotDealsWidget3(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 547.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 345.0,
                              child: GeneratedFrame56Widget6(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 547.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 356.0,
                              child: GeneratedFrame56Widget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 868.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 58.0,
                              child: GeneratedGroup56Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedRectangle162Widget1(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 399.0,
                              height: 730.0,
                              child: GeneratedGroup73Widget1(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 188.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 25.0,
                              child:
                                  GeneratedAntdesignclosecircleoutlinedWidget9(),
                            ),
                            Positioned(
                              left: 133.0,
                              top: 747.0,
                              right: null,
                              bottom: null,
                              width: 167.0,
                              height: 50.0,
                              child: GeneratedGroup64Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
