import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedAnthonyYeboahWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedHowmuchdoyouwanttopayWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedNotificationsWidget13.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedKofiAburiWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedNotificationsWidget11.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedNotificationsWidget9.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedSuziki2020Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedBMW2021Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedRectangle100Widget3.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedRectangle109Widget2.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedMyMessagesWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedUnsplashorWPUp0fRI4Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedUnsplasheTuK4z2LhYWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedAmankwaMotorsWidget7.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedNotificationsWidget14.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedRectangle104Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedNotificationsWidget15.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedGroup56Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedEmilyAsanteWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedNotificationsWidget16.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/Generated1201amWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedNotificationsWidget10.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedWhereareyoulocatedWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedUnsplash62wQhEghaw0Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedRectangle108Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedNotificationsWidget12.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedRectangle107Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedHelloWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedChatsWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedAkariconschevrondownWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedHondaAchordWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedRectangle105Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/Generated155pmWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedToyotaSUVWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedGroup57Widget11.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/Generated320amWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedVectorWidget229.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/Generated330pmWidget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedActiveWidget3.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedNotificationsWidget17.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedRectangle106Widget1.dart';
import 'package:flutterapp/teamapp/generatedmessagewidget2/generated/GeneratedCanyoucometomyofficeWidget1.dart';

/* Frame message
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessageWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 248, 248, 248),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 103.0,
                              child: GeneratedRectangle100Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 42.0,
                              child: GeneratedGroup57Widget11(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.441588785046729;

                                final double height =
                                    constraints.maxHeight * 0.03995680345572354;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2827102803738318,
                                      y: constraints.maxHeight *
                                          0.09935205183585313,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedMyMessagesWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child: GeneratedRectangle104Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child: GeneratedRectangle105Widget1(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 154.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 28.0,
                              child: GeneratedChatsWidget1(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 28.0,
                              child: GeneratedActiveWidget3(),
                            ),
                            Positioned(
                              left: 244.0,
                              top: 154.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget9(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 282.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget10(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 366.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget11(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 460.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget12(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 549.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget13(),
                            ),
                            Positioned(
                              left: 106.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget14(),
                            ),
                            Positioned(
                              left: 106.0,
                              top: 377.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget15(),
                            ),
                            Positioned(
                              left: 106.0,
                              top: 471.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget16(),
                            ),
                            Positioned(
                              left: 109.0,
                              top: 560.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget17(),
                            ),
                            Positioned(
                              left: 377.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedAkariconschevrondownWidget1(),
                            ),
                            Positioned(
                              left: -18.0,
                              top: 231.0,
                              right: null,
                              bottom: null,
                              width: 458.0,
                              height: 90.0,
                              child: GeneratedRectangle106Widget1(),
                            ),
                            Positioned(
                              left: -18.0,
                              top: 319.0,
                              right: null,
                              bottom: null,
                              width: 458.0,
                              height: 90.0,
                              child: GeneratedRectangle107Widget1(),
                            ),
                            Positioned(
                              left: -18.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 458.0,
                              height: 90.0,
                              child: GeneratedRectangle108Widget1(),
                            ),
                            Positioned(
                              left: -15.0,
                              top: 497.0,
                              right: null,
                              bottom: null,
                              width: 458.0,
                              height: 90.0,
                              child: GeneratedRectangle109Widget2(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 241.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedUnsplash62wQhEghaw0Widget1(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedUnsplasheTuK4z2LhYWidget1(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 420.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedUnsplashorWPUp0fRI4Widget1(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 25.0,
                              child: GeneratedKofiAburiWidget1(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 25.0,
                              child: GeneratedAnthonyYeboahWidget1(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 422.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 25.0,
                              child: GeneratedEmilyAsanteWidget1(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 511.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 25.0,
                              child: GeneratedAmankwaMotorsWidget7(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 272.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 23.0,
                              child: GeneratedToyotaSUVWidget1(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 356.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 23.0,
                              child: GeneratedBMW2021Widget1(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 448.0,
                              right: null,
                              bottom: null,
                              width: 98.0,
                              height: 23.0,
                              child: GeneratedSuziki2020Widget1(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 537.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 23.0,
                              child: GeneratedHondaAchordWidget1(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 189.0,
                              height: 20.0,
                              child: GeneratedCanyoucometomyofficeWidget1(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 20.0,
                              child: GeneratedWhereareyoulocatedWidget1(),
                            ),
                            Positioned(
                              left: 115.0,
                              top: 472.0,
                              right: null,
                              bottom: null,
                              width: 211.0,
                              height: 20.0,
                              child: GeneratedHowmuchdoyouwanttopayWidget1(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 561.0,
                              right: null,
                              bottom: null,
                              width: 41.0,
                              height: 23.0,
                              child: GeneratedHelloWidget1(),
                            ),
                            Positioned(
                              left: 338.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 76.0,
                              height: 25.0,
                              child: Generated330pmWidget1(),
                            ),
                            Positioned(
                              left: 338.0,
                              top: 336.0,
                              right: null,
                              bottom: null,
                              width: 76.0,
                              height: 25.0,
                              child: Generated155pmWidget1(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 425.0,
                              right: null,
                              bottom: null,
                              width: 76.0,
                              height: 25.0,
                              child: Generated320amWidget1(),
                            ),
                            Positioned(
                              left: 332.0,
                              top: 514.0,
                              right: null,
                              bottom: null,
                              width: 87.0,
                              height: 25.0,
                              child: Generated1201amWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.16355140186915887;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        70.0;

                                double percentHeight = 0.0755939524838013;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        70.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.07009345794392523,
                                      translateY: constraints.maxHeight *
                                          0.5485961123110151,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget229())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 868.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 58.0,
                              child: GeneratedGroup56Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
