import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/Generated25Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/Generated10NewVisitorsthisWeekWidget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle187Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle192Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle185Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedWeek1Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedFrame81Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/Generated0Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/Generated5Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/Generated20Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle183Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedGroup57Widget7.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedWeek3Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle179Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle190Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle191Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle189Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle180Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedWeek2Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle181Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle182Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle186Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle188Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/Generated15Widget1.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedEvaarrowbackfillWidget2.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedYouhavetwoActiveAdsWidget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle193Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedWeek4Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/Generated6vsLastweekWidget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/GeneratedRectangle184Widget.dart';
import 'package:flutterapp/teamapp/generatedadminmaagementwidget/generated/Generated10Widget.dart';

/* Frame admin maagement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdminmaagementWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 243, 244, 246),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 42.0,
                              child: GeneratedGroup57Widget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 395.0,
                              child: GeneratedRectangle179Widget(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 3.0,
                              child: GeneratedRectangle180Widget(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 3.0,
                              child: GeneratedRectangle181Widget(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 3.0,
                              child: GeneratedRectangle182Widget(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 3.0,
                              child: GeneratedRectangle183Widget(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 346.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 3.0,
                              child: GeneratedRectangle184Widget(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 396.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 3.0,
                              child: GeneratedRectangle185Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 47.0,
                              right: null,
                              bottom: null,
                              width: 277.0,
                              height: 29.0,
                              child: Generated10NewVisitorsthisWeekWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 74.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 23.0,
                              child: Generated6vsLastweekWidget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 388.0,
                              right: null,
                              bottom: null,
                              width: 17.0,
                              height: 28.0,
                              child: Generated0Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 338.0,
                              right: null,
                              bottom: null,
                              width: 17.0,
                              height: 28.0,
                              child: Generated5Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 288.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 28.0,
                              child: Generated10Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 236.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 28.0,
                              child: Generated15Widget1(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 28.0,
                              child: Generated20Widget(),
                            ),
                            Positioned(
                              left: 227.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 56.0,
                              child: GeneratedRectangle190Widget(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 323.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 76.0,
                              child: GeneratedRectangle188Widget(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 154.0,
                              child: GeneratedRectangle186Widget(),
                            ),
                            Positioned(
                              left: 315.0,
                              top: 399.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 30.0,
                              child: GeneratedRectangle192Widget(),
                            ),
                            Positioned(
                              left: 76.0,
                              top: 194.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 205.0,
                              child: GeneratedRectangle187Widget(),
                            ),
                            Positioned(
                              left: 252.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 154.0,
                              child: GeneratedRectangle191Widget(),
                            ),
                            Positioned(
                              left: 164.0,
                              top: 369.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 30.0,
                              child: GeneratedRectangle189Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 138.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 28.0,
                              child: Generated25Widget(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 56.0,
                              child: GeneratedRectangle193Widget(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 402.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 23.0,
                              child: GeneratedWeek1Widget(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 402.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 23.0,
                              child: GeneratedWeek2Widget(),
                            ),
                            Positioned(
                              left: 227.0,
                              top: 402.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 23.0,
                              child: GeneratedWeek3Widget(),
                            ),
                            Positioned(
                              left: 315.0,
                              top: 402.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 23.0,
                              child: GeneratedWeek4Widget(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 22.0,
                              child: GeneratedYouhavetwoActiveAdsWidget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 469.0,
                              right: null,
                              bottom: null,
                              width: 393.0,
                              height: 432.0,
                              child: GeneratedFrame81Widget(),
                            ),
                            Positioned(
                              left: 3.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedEvaarrowbackfillWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
