import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedStatusBarWidget15.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/Generated4Widget1.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/Generated3Widget1.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedRectangle91Widget3.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedVectorWidget225.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedRectangle93Widget1.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/Generated2Widget3.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/Generated1Widget1.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedVectorWidget226.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedVectorWidget224.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedVectorWidget227.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedGroup51Widget1.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedNextWidget1.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedRectangle90Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/teamapp/generatedotpwidget1/generated/GeneratedRectangle92Widget3.dart';

/* Frame otp
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOtpWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.7551631749233353;

                                final double height =
                                    constraints.maxHeight * 0.06431958587844222;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.12149532710280374,
                                      y: constraints.maxHeight *
                                          0.15982721382289417,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup51Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 0.04535637149028078;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedStatusBarWidget15(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.17990654205607476;

                                final double height =
                                    constraints.maxHeight * 0.08315334773218143;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06074766355140187,
                                      y: constraints.maxHeight *
                                          0.33369330453563717,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle90Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.17990654205607476;

                                final double height =
                                    constraints.maxHeight * 0.08315334773218143;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.29439252336448596,
                                      y: constraints.maxHeight *
                                          0.33369330453563717,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle91Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.17990654205607476;

                                final double height =
                                    constraints.maxHeight * 0.08315334773218143;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5280373831775701,
                                      y: constraints.maxHeight *
                                          0.33369330453563717,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle92Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.17990654205607476;

                                final double height =
                                    constraints.maxHeight * 0.08315334773218143;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.7616822429906542,
                                      y: constraints.maxHeight *
                                          0.33369330453563717,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle93Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.7894629362587616;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        337.89013671875;

                                double percentHeight = 0.02050754884921706;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        18.989990234375;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.10514018691588785,
                                      translateY: constraints.maxHeight *
                                          0.4503239740820734,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget224())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.7089250511098131;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        303.419921875;

                                double percentHeight = 0.12016200813309935;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        111.27001953125;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.13551401869158877,
                                      translateY: constraints.maxHeight *
                                          0.5583153347732182,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget225())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.5271960106965538;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        225.639892578125;

                                double percentHeight = 0.018866059074649028;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        17.469970703125;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.24065420560747663,
                                      translateY: constraints.maxHeight *
                                          0.7116630669546437,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget226())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.5514018691588785;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        236.0;

                                double percentHeight = 0.06695464362850972;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        62.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.22897196261682243,
                                      translateY: constraints.maxHeight *
                                          0.8250539956803455,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget227())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.15654205607476634;

                                final double height =
                                    constraints.maxHeight * 0.04319654427645788;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.4322429906542056,
                                      y: constraints.maxHeight *
                                          0.8390928725701944,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedNextWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 52.0,
                              child: Generated4Widget1(),
                            ),
                            Positioned(
                              left: 153.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 52.0,
                              child: Generated3Widget1(),
                            ),
                            Positioned(
                              left: 253.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 52.0,
                              child: Generated2Widget3(),
                            ),
                            Positioned(
                              left: 353.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 52.0,
                              child: Generated1Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
