import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedGroup8Widget8.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedBicaretdownfillWidget26.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedRectangle66Widget2.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedCategoriesWidget2.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedFirstpicturewillbeshownfirstWidget1.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedWelcomeAmankwaMotorsWidget1.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedRectangle64Widget2.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedCancelWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedAdd5photosWidget1.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedPleasegrabanddropphotostochangetheorderWidget1.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedNewAdvertWidget1.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedFrame33Widget1.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedUnsplashSpIKPT8zeAsWidget2.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedBicaretdownfillWidget25.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedVectorWidget153.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedGroup19Widget1.dart';
import 'package:flutterapp/teamapp/generatedmenuwidget1/generated/GeneratedGroup57Widget8.dart';

/* Frame MENU
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMENUWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(249, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.053738317757009345;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        23.0;

                                double percentHeight = 0.02159827213822894;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        20.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.056074766355140186,
                                      translateY: constraints.maxHeight *
                                          0.056155507559395246,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget153())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 8.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 18.0,
                              child: GeneratedGroup8Widget8(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 150.0,
                              child: GeneratedRectangle64Widget2(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 63.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedUnsplashSpIKPT8zeAsWidget2(),
                            ),
                            Positioned(
                              left: 143.0,
                              top: 86.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 34.0,
                              child: GeneratedNewAdvertWidget1(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 28.0,
                              child: GeneratedCancelWidget1(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 214.0,
                              height: 23.0,
                              child: GeneratedWelcomeAmankwaMotorsWidget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 262.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 25.0,
                              child: GeneratedAdd5photosWidget1(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 90.0,
                              child: GeneratedGroup19Widget1(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 392.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 20.0,
                              child:
                                  GeneratedFirstpicturewillbeshownfirstWidget1(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 412.0,
                              right: null,
                              bottom: null,
                              width: 330.0,
                              height: 20.0,
                              child:
                                  GeneratedPleasegrabanddropphotostochangetheorderWidget1(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 51.0,
                              child: GeneratedRectangle66Widget2(),
                            ),
                            Positioned(
                              left: 67.0,
                              top: 210.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 34.0,
                              child: GeneratedCategoriesWidget2(),
                            ),
                            Positioned(
                              left: 358.0,
                              top: 206.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedBicaretdownfillWidget25(),
                            ),
                            Positioned(
                              left: 372.997802734375,
                              top: 239.294189453125,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedBicaretdownfillWidget26(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 42.0,
                              child: GeneratedGroup57Widget8(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 445.0,
                              right: null,
                              bottom: null,
                              width: 362.0,
                              height: 443.0,
                              child: GeneratedFrame33Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
