import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedprofilewidget/generated/GeneratedLogoutWidget.dart';
import 'package:flutterapp/teamapp/generatedprofilewidget/generated/GeneratedGroup57Widget1.dart';
import 'package:flutterapp/teamapp/generatedprofilewidget/generated/GeneratedRectangle64Widget1.dart';
import 'package:flutterapp/teamapp/generatedprofilewidget/generated/GeneratedSeenoevil180gmailcomWidget.dart';
import 'package:flutterapp/teamapp/generatedprofilewidget/generated/GeneratedCisettingsfilledWidget.dart';
import 'package:flutterapp/teamapp/generatedprofilewidget/generated/GeneratedUnsplashSpIKPT8zeAsWidget1.dart';
import 'package:flutterapp/teamapp/generatedprofilewidget/generated/GeneratedFrame58Widget.dart';
import 'package:flutterapp/teamapp/generatedprofilewidget/generated/GeneratedGroup57Widget2.dart';
import 'package:flutterapp/teamapp/generatedprofilewidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/teamapp/generatedprofilewidget/generated/GeneratedAnthonyWalkerWidget.dart';

/* Frame profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(249, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 188.0,
                              child: GeneratedRectangle64Widget1(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 91.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedUnsplashSpIKPT8zeAsWidget1(),
                            ),
                            Positioned(
                              left: 102.0,
                              top: 103.0,
                              right: null,
                              bottom: null,
                              width: 143.0,
                              height: 25.0,
                              child: GeneratedAnthonyWalkerWidget(),
                            ),
                            Positioned(
                              left: 102.0,
                              top: 133.0,
                              right: null,
                              bottom: null,
                              width: 202.0,
                              height: 25.0,
                              child: GeneratedSeenoevil180gmailcomWidget(),
                            ),
                            Positioned(
                              left: 378.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 35.0,
                              height: 35.0,
                              child: GeneratedCisettingsfilledWidget(),
                            ),
                            Positioned(
                              left: 360.0,
                              top: 815.0,
                              right: null,
                              bottom: null,
                              width: 35.0,
                              height: 35.0,
                              child: GeneratedGroup18Widget(),
                            ),
                            Positioned(
                              left: 268.0,
                              top: 820.0,
                              right: null,
                              bottom: null,
                              width: 87.0,
                              height: 31.0,
                              child: GeneratedLogoutWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 42.0,
                              child: GeneratedGroup57Widget1(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 362.0,
                              height: 581.0,
                              child: GeneratedFrame58Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 868.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 58.0,
                              child: GeneratedGroup57Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
