import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/Generated\$50000Widget2.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedStatusBarWidget12.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/Generated\$79000Widget2.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedImage89Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedUSEDENGINE10DISCOUNTWidget1.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedFrame88Widget1.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedGroup78Widget2.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedFrame56Widget1.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedNowWidget7.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedRectangle97Widget1.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedGroup55Widget5.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedAkariconssearchWidget2.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedSearchWidget2.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedGroup53Widget4.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedFrame55Widget1.dart';
import 'package:flutterapp/teamapp/generatedhomepage2widget/generated/GeneratedHotDealsWidget1.dart';

/* Frame HOMEPAGE 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHOMEPAGE2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 252, 252, 252),
                              ),
                            ),
                            Positioned(
                              left: 384.0,
                              top: 455.6836853027344,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 60.0,
                              child: GeneratedUSEDENGINE10DISCOUNTWidget1(),
                            ),
                            Positioned(
                              left: 388.0,
                              top: 472.6836853027344,
                              right: null,
                              bottom: null,
                              width: 114.0,
                              height: 40.0,
                              child: Generated$50000Widget2(),
                            ),
                            Positioned(
                              left: 501.0,
                              top: 480.6836853027344,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 28.0,
                              child: GeneratedNowWidget7(),
                            ),
                            Positioned(
                              left: 394.0,
                              top: 440.6836853027344,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 34.0,
                              child: Generated$79000Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 42.0,
                              child: GeneratedStatusBarWidget12(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 204.0,
                              right: null,
                              bottom: null,
                              width: 395.0,
                              height: 47.0,
                              child: GeneratedFrame55Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 139.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 53.0,
                              child: GeneratedRectangle97Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.06542056074766354;

                                final double height = constraints.maxHeight *
                                    0.023758099352051837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8387850467289719,
                                      y: constraints.maxHeight *
                                          0.08855291576673865,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup78Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 398.0,
                              top: 81.0,
                              right: null,
                              bottom: null,
                              width: 5.0,
                              height: 23.0,
                              child: GeneratedGroup55Widget5(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 153.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 34.0,
                              child: GeneratedSearchWidget2(),
                            ),
                            Positioned(
                              left: 362.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedAkariconssearchWidget2(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 23.0,
                              child: GeneratedHotDealsWidget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 267.0,
                              right: null,
                              bottom: null,
                              width: 387.0,
                              height: 247.0,
                              child: GeneratedFrame56Widget1(),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 104.0,
                              height: 67.0,
                              child: GeneratedImage89Widget1(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 395.0,
                              height: 315.0,
                              child: GeneratedFrame88Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.7990494487441588;

                                final double height = constraints.maxHeight *
                                    0.028096209334503238;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.10046728971962617,
                                      y: constraints.maxHeight *
                                          0.9533643949109071,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup53Widget4(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
