import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedVectorWidget67.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedIamaBuyerWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedVectorWidget61.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedEmailIDWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedIamaSellerWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedConfirmPasswordWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedUserNameWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedCreateanAccountWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedPhoneNumberWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedGroup52Widget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedTermsandConditionsWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedVectorWidget68.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedCoulibalyAdamaWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedAlreadyhaveanAccountWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedVectorWidget60.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedSeenoevil180gmailcomWidget1.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/Generated23323123233Widget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedVectorWidget62.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedStatusBarWidget3.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedVectorWidget65.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedVectorWidget66.dart';
import 'package:flutterapp/teamapp/generatedsignup1widget/generated/GeneratedSigninWidget.dart';

/* Frame SIGN UP 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSIGNUP1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 42.0,
                              child: GeneratedStatusBarWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6728971962616822;

                                final double height =
                                    constraints.maxHeight * 0.04643628509719223;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.1658878504672897,
                                      y: constraints.maxHeight *
                                          0.06587473002159827,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedCreateanAccountWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 157.0,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 72.0,
                              child: GeneratedRectangle11Widget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 266.0,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 72.0,
                              child: GeneratedRectangle12Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 375.0,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 72.0,
                              child: GeneratedRectangle13Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 486.0,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 72.0,
                              child: GeneratedRectangle14Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 596.0,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 72.0,
                              child: GeneratedRectangle16Widget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 886.0,
                              right: null,
                              bottom: null,
                              width: 228.0,
                              height: 25.0,
                              child: GeneratedAlreadyhaveanAccountWidget(),
                            ),
                            Positioned(
                              left: 295.0,
                              top: 886.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 25.0,
                              child: GeneratedSigninWidget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 126.0,
                              right: null,
                              bottom: null,
                              width: 99.0,
                              height: 25.0,
                              child: GeneratedUserNameWidget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 240.0,
                              right: null,
                              bottom: null,
                              width: 74.0,
                              height: 25.0,
                              child: GeneratedEmailIDWidget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 348.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 28.0,
                              child: GeneratedPasswordWidget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 459.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 25.0,
                              child: GeneratedConfirmPasswordWidget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 569.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 25.0,
                              child: GeneratedPhoneNumberWidget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 187.0,
                              height: 31.0,
                              child: GeneratedCoulibalyAdamaWidget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 34.0,
                              child: GeneratedSeenoevil180gmailcomWidget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 397.0,
                              right: null,
                              bottom: null,
                              width: 174.0,
                              height: 40.0,
                              child: GeneratedWidget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 504.0,
                              right: null,
                              bottom: null,
                              width: 174.0,
                              height: 40.0,
                              child: GeneratedWidget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 620.0,
                              right: null,
                              bottom: null,
                              width: 172.0,
                              height: 29.0,
                              child: Generated23323123233Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.054322429906542055;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        23.25;

                                double percentHeight = 0.02510015186944224;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        23.242740631103516;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.06775700934579439,
                                      translateY: constraints.maxHeight *
                                          0.7332613390928726,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget60())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.054322429906542055;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        23.25;

                                double percentHeight = 0.02510015186944224;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        23.242740631103516;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.4929906542056075,
                                      translateY: constraints.maxHeight *
                                          0.7332613390928726,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget61())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.031682379891939255;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        13.56005859375;

                                double percentHeight = 0.010982900664821814;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        10.170166015625;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.0794392523364486,
                                      translateY: constraints.maxHeight *
                                          0.7408207343412527,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget62())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 681.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 25.0,
                              child: GeneratedIamaSellerWidget(),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 708.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 22.0,
                              child: GeneratedTermsandConditionsWidget(),
                            ),
                            Positioned(
                              left: 240.0,
                              top: 681.0,
                              right: null,
                              bottom: null,
                              width: 109.0,
                              height: 25.0,
                              child: GeneratedIamaBuyerWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.0514018691588785;

                                final double height = constraints.maxHeight *
                                    0.016198704103671708;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06775700934579439,
                                      y: constraints.maxHeight *
                                          0.7678185745140389,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup52Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.5514018691588785;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        236.0;

                                double percentHeight = 0.06695464362850972;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        62.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.22429906542056074,
                                      translateY: constraints.maxHeight *
                                          0.8628509719222462,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget65())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.08177570093457943;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        35.0;

                                double percentHeight = 0.03779697624190065;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        35.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.3341121495327103,
                                      translateY: constraints.maxHeight *
                                          0.8045356371490281,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget66())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.08177570093457943;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        35.0;

                                double percentHeight = 0.03779697624190065;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        35.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.45794392523364486,
                                      translateY: constraints.maxHeight *
                                          0.8045356371490281,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget67())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.08411214953271028;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        36.0;

                                double percentHeight = 0.03779697624190065;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        35.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.5817757009345794,
                                      translateY: constraints.maxHeight *
                                          0.8045356371490281,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget68())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 812.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 37.0,
                              child: GeneratedSignUpWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
