import 'package:flutter/material.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedStatusBarWidget10.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedSubmitWidget.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedForgotPasswordWidget1.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedGroup82Widget1.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedPleaseenteryourregisteredEmailIDtoresetyourpasswordWewi.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/Generated31Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedRectangle11Widget2.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedRememberPasswordWidget.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedVectorWidget132.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedRectangle238Widget.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedEmailIDWidget2.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedSigninWidget1.dart';
import 'package:flutterapp/teamapp/generatedpasswordresetwidget/generated/GeneratedSeenoevil180gmailcomWidget3.dart';

/* Frame PASSWORD RESET
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPASSWORDRESETWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 42.0,
                              child: GeneratedStatusBarWidget10(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.5327102803738317;

                                final double height =
                                    constraints.maxHeight * 0.15982721382289417;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2336448598130841,
                                      y: constraints.maxHeight *
                                          0.12958963282937366,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated31Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 219.0,
                              height: 29.0,
                              child: GeneratedGroup82Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 346.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 580.0,
                              child: GeneratedRectangle238Widget(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 370.0,
                              right: null,
                              bottom: null,
                              width: 273.0,
                              height: 43.0,
                              child: GeneratedForgotPasswordWidget1(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 72.0,
                              child: GeneratedRectangle11Widget2(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 74.0,
                              height: 25.0,
                              child: GeneratedEmailIDWidget2(),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 633.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 34.0,
                              child: GeneratedSeenoevil180gmailcomWidget3(),
                            ),
                            Positioned(
                              left: 82.0,
                              top: 878.0,
                              right: null,
                              bottom: null,
                              width: 199.0,
                              height: 25.0,
                              child: GeneratedRememberPasswordWidget(),
                            ),
                            Positioned(
                              left: 288.0,
                              top: 878.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 25.0,
                              child: GeneratedSigninWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 424.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 71.0,
                              child:
                                  GeneratedPleaseenteryourregisteredEmailIDtoresetyourpasswordWewi(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.5514018691588785;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        236.0;

                                double percentHeight = 0.06695464362850972;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        62.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.23598130841121495,
                                      translateY: constraints.maxHeight *
                                          0.838012958963283,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget132())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 170.0,
                              top: 789.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 40.0,
                              child: GeneratedSubmitWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
